### PR TITLE
fix:  Resolve issues on Touchpoint GUI editor & time picker

### LINKED ISSUE #51: GUI editor mangling the measure_time in some cases
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

When a time window other than the Time-Picker default is selected, for example, "60 minutes ago", all touchpoints that did not have measure_time are temporarily calculated from the Time-Picker selection (SINCE 1668428490 UNTIL 1668428790). This change becomes permanent if the Touchpoints GUI editor is opened and the “Save Update” button is clicked.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

1. To verify the Touchpoints GUI editor before making changes in the Time-Picker.

image

2. Change the selection in the Time-Picker to 30 minutes:

image

3. The touchpoint graphic editor opens and clicks on the “Save Update” button.
 
4. The Pathpoint is reloaded with the Time-Picker in its default selection and the graphical editor of touchpoints is opened. It is evident that all the touchpoints that did not have a custom measure_time have been modified:

image

5. Likewise, the touchpoints that have the custom measure_time are not affected by the action of the GUI editor:

image

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

Touchpoints GUI editor should not save changes in measure_time with Time-Picker effects.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/2.83.5 win32-x64 node-v16.11.1
* Browser name and version: Firefox 107.0 (64 bit)
* Operating System and version: Windows 10
* Pathpoint version: 1.7.3

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

### LINKED ISSUE #52: `measure_time` is not being treated case insensitively (ignores lower case)
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

If in the JSON config file the measure_time is defined as "5 minutes ago", using lower case, this is interpreted as custom. The measure_time is only considered by default when it is set to uppercase with the value of “5 MINUTES AGO”. This causes the Time-Picker to have no effect on those touchpoints and can be confusing for the user.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

1. Enter the Pathpoint menu to download the JSON config file.

image

2. Select the “Json configuration” option from the menu and then click the download button.

image

3. In the JSON config file, you can see the measute_time properties in lowercase and uppercase of two touchpoints of the same type.

image

4. When the Time-Picker is selected for example in “60 minutes ago” and we download the JSON-FILE again, we observe that this selection only has an effect on the touchpoints with the measure_time defined in uppercase, the touchpoints with the time defined in lowercase they are not affected because it is considered as custom:

image

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

The interpreter of the measure_time attribute must recognize the default value of "5 Minutes Ago" with a case-insensitive filter.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/2.83.5 win32-x64 node-v16.11.1
* Browser name and version: Firefox 107.0 (64 bit)
* Operating System and version: Windows 10
* Pathpoint version: 1.7.3

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

### PR DESCRIPTION
**Pull request by portoren**
fix: resolves #51, resolves #52

### CODE REVIEW

File: nerdlets/pathpoint-nerdlet/components/Modal/TouchpointsEditor.js [hunk 1]
```diff
@@ -903,17 +929,70 @@ class BodyTouchpointsEditor extends Component {
...
+        break;
+      case '24 HOURS AGO':
+        time_start = Math.floor(Date.now() / 1000) - 24 * 60 * 60 - 5 * 60;
+        time_end = Math.floor(Date.now() / 1000) - 24 * 60 * 60;
+        break;
+      case '3 DAYS AGO':
+        time_start = Math.floor(Date.now() / 1000) - 3 * 24 * 60 * 60 - 5 * 60;
+        time_end = Math.floor(Date.now() / 1000) - 3 * 24 * 60 * 60;
+        break;
+      case '7 DAYS AGO':
```
Comment (JimHagan) [inline nerdlets/pathpoint-nerdlet/components/Modal/TouchpointsEditor.js:967]: @portoren I found a bug here.


`7 Days Ago` is using 3 days -- so it is identical to `3 Days Ago`

Comment (portoren) [reply nerdlets/pathpoint-nerdlet/components/Modal/TouchpointsEditor.js:967]: Done

**Review by JimHagan — APPROVED** [review]
I approve these changes and have tested on this branch for a few days.  We will do some more testing prior to deploying to the NR1 catalog.
